### ISSUE TITLE
Set another parent for images

### ISSUE THREAD

**Issue by patrickroeder** [getkirby/editor#124]
As of now, the image block in the editor "pulls" image files only from the current page. It would be great to be able to set another parent for images, e.g. a different page or the entire site, the sort of stuff you can normally do using a query option for files fields in a page blueprint.

**Comment by bnomei** [comment]
if parent is set to another page uploading files in editor image block should be disabled?

**Comment by patrickroeder** [comment]
My expectation was that a image block works similarly to a files field. Therefore I would probably implement it along the lines of how it already works for a files field, see: https://getkirby.com/docs/reference/panel/fields/files#upload-options__destination-and-template

So default is the current page, and a parent could be defined to set the upload destination. Tbh in my particular case I just disabled the upload button altogether because I could see no way to set a template for uploaded files, which in my case is essential. 

So the gist of it is: Provide options like in a files field, with querying being the most essential option. Just a suggestion -- don't know how realistic/feasible it is to implement it.

**Comment by bastianallgeier** [comment]
I think you will be happy to hear that all of this is already possible :) 

```yml
fields:
  text:
    type: editor
    files:
      query: site.find("photos").files
    uploads:
      parent: site.find("photos")
      template: editor-image
```
