### ISSUE TITLE
Any way to add a blueprint to the image?

### ISSUE THREAD

**Issue by ktryndchrs** [getkirby/editor#131]
When I want to edit the image from the editor, this is what I get (as illustrated in the link below)
https://jmp.sh/bBH3X7U

😅😅😅

**Comment by bastianallgeier** [comment]
You can set a default blueprint for all files by creating `/site/blueprints/files/default.yml` but you can also set which template should be used for uploaded images in the editor: 

```yml
fields: 
  editor: 
    type: editor
    uploads: 
      template: my-custom-image-template
```
