### ISSUE TITLE
Input Focus out of bounds

### ISSUE THREAD

**Issue by findthebug** [getkirby/editor#162]
Kirby 3.3.0
Editor 1.0.0

There seems to be a problem within the editor-field focus if i add or save stuff in the editor.

Have 2 column setup in the blueprint as shown below. Added the editor on the left column at the last position. The focus is jumping to the last field on the right colum, if i save or change stuff in the editor area.

The editor field is now blocked and out of focus. It's also not possible to go back to the editor field with the mouse cursor, just a reload solves the focus problem.

 
![Bildschirmfoto 2019-11-07 um 16 48 04](https://user-images.githubusercontent.com/5121132/68404226-80679300-017e-11ea-9b72-42737c9611b3.png)
 
```yml
 
columns:
  left___content:
    width: 2/3
    sections:
      section___content:
        type: fields
        # other fields .....
        fields:
          pubicDate:
            type: date
            label: Datum
            width: 1/2
            required: true
          newsEditor:
            type: editor
            label: Inhalte

  right___content:
    width: 1/3
    sections:
      section___1:
        type: fields
        fields:
         # other fields .....
         #->>>>>> jumpt to this after saving 
        categories:
            width: 1/2
            label: Sichtbarkeit
            type: checkboxes
            help: Wählen Sie die Sichtbarkeit für die News
            columns: 2
            min: 1
            max: 2
            options:
              rheinregulierung: Rheinregulierung
              rhesi: Rhesi

```
