### ISSUE TITLE
Ability to setup upload destination and template for image uploads

### ISSUE THREAD

**Issue by tideg** [getkirby/editor#202]
While it is possible to set a custom query for the file selection inside an image block via blueprint, it seems that there is currently no option to set the destination for an image upload nor the template which should be used therefore.

Just for the note: You can setup a custom query via:
```
editorField:
  label: Editor
  type: editor
  files:
    query: page.parent
```

**Comment by tideg** [comment]
My bad, just found the options:

```
editorField:
  label: Editor
  type: editor
  files:
    query: page.parent
  uploads:
    parent: page.parent
    template: image
```
