### ISSUE TITLE
Help not displayed below editor field

### ISSUE THREAD

**Issue by RomanWu** [getkirby/editor#210]
**Describe the bug**
When the blueprint for the editor field contains a "help" text, it is not displayed below the editor.

**To Reproduce**
Blueprint:
```
fields:
    text:
        type: editor
        help: This is a help text (not displayed)
    text2:
        type: textarea
        help: This is a help text (displayed)
```

**Expected behavior**
Both help texts displayed.

**Kirby Version**
Tried Kirby 3.3.0 and Kirby 3.3.4, with Editor 1.0.2
