### ISSUE TITLE
Limit block number

### ISSUE THREAD

**Issue by isaactopo** [getkirby/editor#226]
It would be interesting to be able to limit the number of blocks to add. For example, for use only one paragraph block. And exclude the dropdown “insert below” and “Duplicate”. With this you can use the field as a textarea with the WYSIWYG view. It makes sense?

**Comment by texnixe** [comment]
For a **single** paragraph with inline styles, you can use the inline option:
```
fields: 
  text: 
    type: editor
    inline: true
```
It allows inline styles, but you cannot add any other blocks.
