### ISSUE TITLE
Editor field content in structure does not update when switching to the next structure item

### ISSUE THREAD

**Issue by tritos-design** [getkirby/editor#231]
Error description:
When an editor field is nested in a structure and I switch from one structure item A to the next one B by clicking on the pagination arrows, the editor field content stays unchanged. Inspecting the txt file reveals that the content is stored correctly in A and B. The problem is just that the editor content is not updated when switching structure items directly. The same happens when item B is opened first and then switched to item A by clicking on the pagination arrows.

Expected:
Editor field updates content when switching between structure items.

Precondition:
Blueprint as follows:
```
activities:
  label: Activities
  type: structure
  fields:
    name:
      label: Activity name
      type: text
    content:
      label: Text
      type: editor
      pretty: false
```

Steps to reproduce the error:
1) Add content to two structure items and save.
2) In the structure overview (typically the page view in the panel) click on the first item.
3) Switch to the second item by hitting the right arrow below the structure item.
