### ISSUE TITLE
Option for choosing a default block 

### ISSUE THREAD

**Issue by HYR** [getkirby/editor#267]
There are times when I want to show all options to the user about what can be inserted as a block in the editor field, but there are also times I'd like to just allow people to start typing text. 

I'm suggesting a `default` option that allows you to choose the block to start with.

```
fields:
  text:
    label: Editor
    type: editor
    default: h2
```
or 
```
fields:
  text:
    label: Editor
    type: editor
    default: paragraph
```

https://forum.getkirby.com/t/editor-plugin-default-to-text-block/19703
