### ISSUE TITLE
Feature: Umlauts in content files

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#31]
I see this is in my content file:

```yml
[
    {
        "attrs": [],
        "content": "Unsere Umgebung ver\u00e4ndert sich. Mal unmerklich, mal ganz offensichtlich. In seinem Projekt <a href=\"http://zeitsprung.animaux.de\">Zeitsprung</a> bringt Alexander Rutz das Gestern und Heute der Stadt Weimar fotografisch zur Deckung.",
        "id": "_9obatb19c",
        "type": "paragraph"
    }
]
```

Notice the `\u00e4` for an `ä`. Is that encoding intended?
